apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello3-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-hello3
        image: douklias/hello3
        ports:
        - containerPort: 80
